'use client'

import Link from 'next/link'
import { useState } from 'react'
import { ArrowDownRight, ArrowRight, Menu, X, Instagram, Linkedin, MessageCircle } from 'lucide-react'

export const whatsappNumber = ''
const whatsappHref = whatsappNumber ? `https://wa.me/${whatsappNumber}` : '#contato'

const cases = [
  { name: 'BLACK BULL', result: 'R$5 mil → R$70 mil/mês', detail: '14x de crescimento em 6 meses', tags: 'Branding · Performance · Vendas · Automação', tone: 'orange', href: '/cases/black-bull' },
  { name: 'SONHO DE CRIANÇA', result: 'R$10 mil → R$100 mil/mês', detail: '10x de crescimento', tags: 'Marketing · Performance · SEO · Comercial', tone: 'cream', href: '/cases/sonho-de-crianca' },
  { name: 'OBJETIVO', result: '1.377 leads → 126 matrículas', detail: 'Marketing conectado à jornada comercial', tags: 'Estratégia · Posicionamento · Performance', tone: 'blue', href: '/cases/objetivo-barao-geraldo' },
  { name: 'PRIVILLEGE', result: 'Uma nova identidade de marca', detail: 'Percepção alinhada ao produto', tags: 'Branding · Identidade Visual', tone: 'purple', href: '/cases/privillege' },
]

export function Container({ children, className = '' }: { children: React.ReactNode; className?: string }) {
  return <div className={`mx-auto w-full max-w-[1240px] px-6 lg:px-10 ${className}`}>{children}</div>
}

export function Header() {
  const [open, setOpen] = useState(false)
  return <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-[#0a0a0a]/85 backdrop-blur-xl">
    <Container className="flex h-[76px] items-center justify-between">
      <Link href="/" className="font-display text-lg font-semibold tracking-tight text-white">Gustavo<span className="text-[#ff5b1f]">.</span></Link>
      <nav className="hidden items-center gap-8 text-[13px] text-white/60 md:flex">
        <Link className="transition hover:text-white" href="/">Home</Link><Link className="transition hover:text-white" href="/sobre">Sobre</Link><Link className="transition hover:text-white" href="/servicos">Serviços</Link><Link className="transition hover:text-white" href="/cases">Cases</Link><Link className="transition hover:text-white" href="/metodo">Método</Link>
      </nav>
      <a href={whatsappHref} className="hidden rounded-full bg-gradient-to-r from-[#ff7a36] to-[#f44c16] px-5 py-2.5 text-[12px] font-bold text-white shadow-[0_0_25px_rgba(255,91,31,.2)] transition hover:scale-105 md:block">Vamos conversar <ArrowRight className="ml-2 inline h-3.5 w-3.5" /></a>
      <button aria-label="Abrir menu" onClick={() => setOpen(!open)} className="text-white md:hidden">{open ? <X /> : <Menu />}</button>
    </Container>
    {open && <nav className="border-t border-white/10 bg-[#0a0a0a] px-6 py-6 md:hidden"><div className="flex flex-col gap-5 text-sm text-white/70"><Link onClick={() => setOpen(false)} href="/">Home</Link><Link onClick={() => setOpen(false)} href="/sobre">Sobre</Link><Link onClick={() => setOpen(false)} href="/servicos">Serviços</Link><Link onClick={() => setOpen(false)} href="/cases">Cases</Link><Link onClick={() => setOpen(false)} href="/metodo">Método</Link></div></nav>}
  </header>
}

export function WhatsAppFloat() { return <a href={whatsappHref} aria-label="Falar pelo WhatsApp" className="fixed bottom-6 right-6 z-40 flex h-14 w-14 items-center justify-center rounded-full bg-[#ff5b1f] text-white shadow-[0_8px_30px_rgba(255,91,31,.35)] transition hover:scale-110"><MessageCircle className="h-6 w-6" /></a> }

export function PageFrame({ children }: { children: React.ReactNode }) { return <div className="min-h-screen bg-[#0a0a0a] text-white"><Header />{children}<WhatsAppFloat /><Footer /></div> }

export function Footer() { return <footer className="border-t border-white/10 py-10"><Container className="flex flex-col justify-between gap-5 text-sm text-white/40 md:flex-row"><span>© 2026 Gustavo Moscardi</span><div className="flex gap-5"><a href="#" className="hover:text-white"><Instagram className="h-4 w-4" /></a><a href="#" className="hover:text-white"><Linkedin className="h-4 w-4" /></a><span>Marketing · Growth · Strategy</span></div></Container></footer> }

export function SectionLabel({ children }: { children: React.ReactNode }) { return <div className="mb-7 flex items-center gap-3 text-[10px] font-bold uppercase tracking-[.24em] text-[#ff6a2a]"><span className="h-px w-8 bg-[#ff6a2a]" />{children}</div> }

export function Stats() { return <section className="border-y border-white/10 bg-[#101010] py-20"><Container><SectionLabel>Experiência em números</SectionLabel><div className="grid gap-10 md:grid-cols-3">{[['3', 'anos de experiência em marketing'], ['+60', 'projetos desenvolvidos'], ['+R$ 2M', 'em mídia gerenciada']].map(([n, t]) => <div key={n}><div className="font-display text-5xl font-bold tracking-tight text-white md:text-7xl">{n}<span className="text-[#ff5b1f]">.</span></div><p className="mt-3 text-sm text-white/45">{t}</p></div>)}</div><p className="mt-16 max-w-md text-lg leading-relaxed text-white/60">Do branding à performance.<br />Da aquisição à estratégia comercial.</p></Container></section> }

export function CaseCard({ item }: { item: typeof cases[number] }) { return <Link href={item.href} className="group relative block min-h-[360px] overflow-hidden rounded-2xl border border-white/10 bg-[#171717] p-7 transition duration-500 hover:-translate-y-1 hover:border-[#ff5b1f]/70"><div className={`absolute inset-0 opacity-40 transition duration-500 group-hover:opacity-70 ${item.tone === 'orange' ? 'bg-[radial-gradient(circle_at_80%_20%,#ff5b1f,transparent_48%)]' : item.tone === 'cream' ? 'bg-[radial-gradient(circle_at_80%_20%,#ca9b71,transparent_48%)]' : item.tone === 'blue' ? 'bg-[radial-gradient(circle_at_80%_20%,#31528b,transparent_48%)]' : 'bg-[radial-gradient(circle_at_80%_20%,#8b4e9c,transparent_48%)]'}`} /><div className="relative flex h-full flex-col justify-between"><div className="flex items-start justify-between"><span className="text-[10px] tracking-[.2em] text-white/40">CASE 0{cases.indexOf(item) + 1}</span><ArrowDownRight className="h-5 w-5 text-white/50 transition group-hover:rotate-[-45deg] group-hover:text-[#ff7a36]" /></div><div><p className="mb-3 text-xs font-bold tracking-[.18em] text-[#ff7a36]">{item.name}</p><h3 className="max-w-xs font-display text-2xl font-semibold leading-tight">{item.result}</h3><p className="mt-3 text-sm text-white/55">{item.detail}</p><p className="mt-8 text-[11px] text-white/40">{item.tags}</p></div></div></Link> }

export function CasesGrid() { return <section id="cases" className="py-28"><Container><div className="mb-12 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><SectionLabel>Cases em destaque</SectionLabel><h2 className="max-w-xl font-display text-4xl font-semibold tracking-tight md:text-6xl">Projetos que saíram<br /><span className="text-white/35">do papel.</span></h2></div><Link href="/cases" className="text-sm text-white/60 transition hover:text-[#ff7a36]">Ver todos os cases <ArrowRight className="ml-2 inline h-4 w-4" /></Link></div><div className="grid gap-4 md:grid-cols-2">{cases.map((item) => <CaseCard key={item.name} item={item} />)}</div></Container></section> }

export function MethodPreview() { const steps = [['01', 'DIAGNÓSTICO', 'Entender o negócio e encontrar as oportunidades.'], ['02', 'ESTRATÉGIA', 'Definir direção, canais e posicionamento.'], ['03', 'EXECUÇÃO', 'Transformar estratégia em ação.'], ['04', 'ANÁLISE', 'Medir, aprender e identificar gargalos.'], ['05', 'CRESCIMENTO', 'Otimizar o que funciona e construir escala.']]; return <section className="bg-[#f2eee9] py-24 text-[#111]"><Container><div className="grid gap-14 lg:grid-cols-[.8fr_1.4fr]"><div><SectionLabel>Meu método</SectionLabel><h2 className="font-display text-4xl font-semibold tracking-tight md:text-6xl">Como eu<br /><span className="text-[#ff5b1f]">trabalho.</span></h2><p className="mt-8 max-w-xs text-sm leading-relaxed text-black/55">Marketing não termina quando a campanha é publicada. É aí que começa o aprendizado.</p></div><div className="space-y-0">{steps.map(([n, t, d]) => <div key={n} className="group flex gap-6 border-t border-black/15 py-6"><span className="font-display text-sm font-bold text-[#ff5b1f]">{n}</span><div><h3 className="font-display text-lg font-bold tracking-wide">{t}</h3><p className="mt-2 text-sm text-black/55">{d}</p></div><ArrowRight className="ml-auto h-5 w-5 opacity-30 transition group-hover:translate-x-1 group-hover:text-[#ff5b1f]" /></div>)}</div></div></Container></section> }

export function FinalCTA() { return <section id="contato" className="relative overflow-hidden py-28"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_40%,rgba(255,91,31,.22),transparent_40%)]" /><Container className="relative"><SectionLabel>Próximo passo</SectionLabel><h2 className="max-w-3xl font-display text-5xl font-semibold tracking-tight md:text-8xl">Tem um desafio<br /><span className="text-[#ff5b1f]">de marketing?</span></h2><p className="mt-8 max-w-md text-lg text-white/55">Vamos entender o problema e encontrar a oportunidade.</p><a href={whatsappHref} className="mt-10 inline-flex items-center rounded-full bg-white px-6 py-4 text-sm font-bold text-black transition hover:bg-[#ff5b1f] hover:text-white">Falar comigo pelo WhatsApp <ArrowRight className="ml-3 h-4 w-4" /></a></Container></section> }

export { cases }

export function Hero() { return <section className="relative overflow-hidden pt-32 pb-20 md:pt-44 md:pb-32"><div className="absolute right-0 top-0 h-[700px] w-[55%] bg-[radial-gradient(ellipse_at_center,rgba(255,91,31,.16),transparent_65%)]" /><Container className="relative grid items-center gap-16 lg:grid-cols-[1.02fr_.98fr]"><div><div className="mb-7 flex items-center gap-3 text-xs uppercase tracking-[.22em] text-white/45"><span className="h-2 w-2 rounded-full bg-[#ff5b1f] shadow-[0_0_14px_#ff5b1f]" /> Marketing & Growth Strategist</div><h1 className="font-display text-[clamp(3.5rem,8vw,7.8rem)] font-semibold leading-[.88] tracking-[-.07em]">Gustavo<br /><span className="text-white/35">Moscardi</span><span className="text-[#ff5b1f]">.</span></h1><p className="mt-10 max-w-lg text-xl leading-relaxed text-white/65">Estratégia, marketing e crescimento para negócios que querem transformar oportunidades em resultados.</p><p className="mt-8 border-l border-[#ff5b1f] pl-4 text-sm italic text-white/45">Eu não penso apenas no anúncio.<br />Eu penso no caminho inteiro.</p><div className="mt-10 flex flex-wrap gap-3"><a href="#cases" className="rounded-full bg-gradient-to-r from-[#ff7a36] to-[#f44c16] px-6 py-3.5 text-sm font-bold transition hover:scale-105">Conheça meu trabalho <ArrowDownRight className="ml-2 inline h-4 w-4" /></a><a href={whatsappHref} className="rounded-full border border-white/20 px-6 py-3.5 text-sm font-bold transition hover:border-white hover:bg-white hover:text-black">Vamos conversar</a></div></div><div className="relative mx-auto w-full max-w-[490px]"><div className="absolute -inset-5 rounded-[2rem] border border-[#ff5b1f]/20" /><div className="relative aspect-[.84] overflow-hidden rounded-2xl bg-[#1c1c1c]"><img src="/gustavo-portrait.png" alt="Retrato editorial de Gustavo Moscardi" className="h-full w-full object-cover grayscale-[.15]" /><div className="absolute inset-0 bg-gradient-to-t from-[#0a0a0a] via-transparent to-transparent" /><div className="absolute bottom-6 left-6 text-[10px] uppercase tracking-[.2em] text-white/55">Estratégia que move negócios</div></div><div className="absolute -bottom-8 -left-8 flex h-24 w-24 items-center justify-center rounded-full bg-[#ff5b1f] text-center text-[10px] font-bold uppercase leading-tight tracking-widest text-white">Think<br />different</div></div></Container></section> }

export function HomePage() { return <PageFrame><Hero /><Stats /><section className="py-28"><Container><div className="grid gap-16 lg:grid-cols-[.75fr_1.25fr] lg:items-end"><div><SectionLabel>Como eu penso</SectionLabel><h2 className="font-display text-4xl font-semibold leading-[.95] tracking-tight md:text-6xl">Marketing começa<br /><span className="text-[#ff5b1f]">antes da campanha.</span></h2></div><div><p className="max-w-lg text-xl leading-relaxed text-white/65">Antes de pensar em anúncio, eu procuro entender o negócio.</p><div className="mt-10 flex max-w-xl flex-wrap gap-2">{['Mercado','Público','Oferta','Posicionamento','Concorrência','Aquisição','Comercial','Dados'].map((word) => <span key={word} className="rounded-full border border-white/15 px-4 py-2 text-xs text-white/60 transition hover:border-[#ff5b1f] hover:text-[#ff7a36]">{word}</span>)}</div><p className="mt-12 text-sm italic text-white/45">Eu não penso apenas no anúncio. Eu penso no caminho inteiro.</p></div></div></Container></section><CasesGrid /><MethodPreview /><section className="py-24"><Container className="grid gap-10 border-t border-white/10 pt-20 md:grid-cols-[.8fr_1.2fr]"><div><SectionLabel>Sobre mim</SectionLabel><h2 className="font-display text-4xl font-semibold tracking-tight md:text-6xl">Mais do que<br /><span className="text-white/35">campanhas.</span></h2></div><div><p className="max-w-xl text-xl leading-relaxed text-white/65">Sou Gustavo Moscardi, profissional de marketing com experiência em estratégia, branding, performance, vendas e automação.</p><p className="mt-5 max-w-xl text-white/45">Já desenvolvi mais de 60 projetos em diferentes negócios e mercados.</p><Link href="/sobre" className="mt-8 inline-flex items-center text-sm font-bold text-[#ff7a36]">Conheça minha trajetória <ArrowRight className="ml-2 h-4 w-4" /></Link></div></Container></section><FinalCTA /></PageFrame> }

export function InnerHero({ eyebrow, title, accent, children }: { eyebrow: string; title: string; accent: string; children?: React.ReactNode }) { return <section className="pt-40 pb-24"><Container><SectionLabel>{eyebrow}</SectionLabel><h1 className="max-w-5xl font-display text-6xl font-semibold leading-[.9] tracking-[-.06em] md:text-9xl">{title}<br /><span className="text-[#ff5b1f]">{accent}</span></h1>{children}</Container></section> }

export function ServiceCards() { const items = [['01', 'ESTRATÉGIA', 'Direção de marketing baseada no negócio, mercado e oportunidades.'], ['02', 'BRANDING', 'Construção de marcas, identidade e posicionamento.'], ['03', 'PERFORMANCE', 'Campanhas e aquisição através de mídia e canais digitais.'], ['04', 'CONTEÚDO', 'Comunicação estratégica para fortalecer presença e posicionamento.'], ['05', 'COMERCIAL', 'Estruturação da jornada entre lead, oportunidade e venda.'], ['06', 'AUTOMAÇÃO', 'Tecnologia e inteligência artificial aplicadas à operação.']]; return <div className="grid gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/10 md:grid-cols-2 lg:grid-cols-3">{items.map(([n,t,d]) => <div key={n} className="group bg-[#121212] p-8 transition hover:bg-[#1c1c1c]"><span className="text-xs text-[#ff5b1f]">{n}</span><h2 className="mt-16 font-display text-xl font-bold">{t}</h2><p className="mt-3 text-sm leading-relaxed text-white/45">{d}</p></div>)}</div> }

export function CaseList() { return <section className="pb-28"><Container><div className="grid gap-4 md:grid-cols-2">{cases.map((item) => <CaseCard key={item.name} item={item} />)}</div></Container></section> }

export function CaseDetail({ name, title, result, stats, tags }: { name: string; title: string; result: string; stats: string[]; tags: string[] }) { return <PageFrame><InnerHero eyebrow={`Case · ${name}`} title={title} accent="resultado." /><Container><div className="grid gap-6 border-y border-white/10 py-12 md:grid-cols-[1.2fr_.8fr]"><div><span className="text-xs uppercase tracking-[.2em] text-white/40">Resultado principal</span><h2 className="mt-5 font-display text-5xl font-semibold text-[#ff6b2a] md:text-7xl">{result}</h2></div><div className="grid grid-cols-2 gap-5">{stats.map((s) => <div key={s} className="border-l border-[#ff5b1f] pl-4 text-sm text-white/65">{s}</div>)}</div></div><div className="grid gap-10 py-24 md:grid-cols-[.65fr_1.35fr]"><div><SectionLabel>Escopo</SectionLabel><div className="flex flex-wrap gap-2">{tags.map((t) => <span key={t} className="rounded-full border border-white/15 px-3 py-2 text-xs text-white/60">{t}</span>)}</div></div><div className="min-h-[320px] rounded-2xl border border-dashed border-white/20 bg-[#111] p-8"><span className="text-xs uppercase tracking-[.2em] text-white/25">Espaço reservado para imagens do projeto</span><div className="flex h-full items-center justify-center text-center font-display text-2xl text-white/15">Imagens, criativos<br />e resultados visuais</div></div></div></Container><FinalCTA /></PageFrame> }

export { cases as caseData }
